@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

'Client Package
package "Client class"{
class Main
}

'Utility Package
package "Utility classes"{
class UserInterface
class InputOutput
}

'Entity Package
package "Entity classes"{
class Movie
class Serie
class Application
class User
abstract Media
}

'Label on Relations !MANGLER
Application *-- UserInterface
Application *-- InputOutput
Application *-- User
Application *-- Media
Media <|-- Serie
Media <|-- Movie
InputOutput *-- Movie
InputOutput *-- Serie
Main *-- Application
User *-- UserInterface

'Class Methods & Attributes
Main : + Application app

Application : - List<User> users
Application : - Set<User> users
Application : - IO io;
Application : - UI ui;
Application : + void launchApplication()
Application : + void startMenu()
Application : + void createUser()
Application : + boolean login()
Application : + void mainMenu()
Application : + Media search()
Application : + Set<Media> filter()
Application : + void chooseMedia()
Application : + void playMedia()

User : - String name
User : - String userName
User : - String password
User : - Set<Media> watched
User : - Set<Media> saved
User : - String checkUserName(String userName)
User : - String checkPassword(String password)
User : + User(String name, String userName, String password)
User : + String getName()
User : + String getUserName()
User : + String getPassword()
User : + void changeName(String name)
User : + void changeUserName(String userName)
User : + void changePassword(String (password)
User : + Set<Media> getWatched()
User : + Set<Media> getSaved()
User : + void addWatchedMedia(Media m)
User : + void addSavedMedia(Media m)


InputOutput : - File file
InputOutput : - Scanner scan
InputOutput : - List<Media> list = new ArrayList<>()
InputOutput : + List<String> readData (String path)
InputOutput : + void saveUsers (String path, List<User> userList)
InputOutput : + List<Media> readMovieData()

UserInterface : - Scanner scan = new Scanner (System.in)
UserInterface : + void displayMessage(String msg)
UserInterface : + String getInput(String msg)

Media : - Scanner scan = new Scanner (System.in)
Media : - String[] categories
Media : - float rating
Media : - int releaseYear
Media : - String titel
Media : + Media(String title, String[] categories, float rating, int releaseYear)
Media : + String getTitle()
Media : + String[] getCategories()
Media : + float getRating()
Media : + int getReleaseYear()

Movie : + Movie(String title, String category, float rating, int releaseYear)

@enduml