@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

(Main) <-- (Application)
(Application) <-- (User)
(Application) <-- (Media)
(Application) <-- (UI)
(Application) <-- (IO)
(Media) <-- (Movie)

@enduml