@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

'Utility Package
package "Utility classes"{
class Main
class UserInterface
class InputOutput
}

'Entity Package
package "Entity classes"{
class Movie
class Serie
class Application
class User
abstract Media
}

'Class Relations
Application *-- UserInterface
Application *-- InputOutput
Application *-- User
Application *-- Media
Media <|-- Serie
Media <|-- Movie
Main *-- Application

'Class Methods & Attributes

@enduml